version: '3'
services:
  neo4j:
    image: neo4j:latest
    container_name: torch_db
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - .env
    volumes:
      - ./db/data:/data
      - ./db/logs:/logs
      - ./db/import:/import
    networks:
      - torch-net
  echo-server:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: torch_api
    ports:
      - "1323:1323"
    env_file:
      - .env
    networks:
      - torch-net
networks:
  torch-net:
    driver: bridge